### ISSUE TITLE
How to use instance profile credentials

### ISSUE THREAD

**Issue by ahaaje** [seferov/awsBundle#2]
EC2 instances can provide instance profile credentials, to use instead of a user key pair. The [SDK quick start guide] (http://docs.aws.amazon.com/aws-sdk-php/guide/latest/quick-start.html) has this to say

"**You can also choose to forgo specifying credentials if you are relying on instance profile credentials**". I tried configuring the bundle with setting they key and secret to null

seferov_aws:
    key: null
    secret: null

This give this error

[Symfony\Component\Config\Definition\Exception\InvalidConfigurationException]  
  The path "seferov_aws.key" cannot contain an empty value, but got null.

Is there some other way to use instance profile credentials?

**Comment by seferov** [comment]
Hi @ahaaje could you please test it with this release: https://github.com/seferov/awsBundle/tree/1.1.2

**Comment by ahaaje** [comment]
Hi @seferov ! Thanks for the update. I can confirm leaving out the key and secret no longer generate an automatic error, but I have not yet been able to test with instance credentials as the application is currently only on a dev. machine.

I will update when tested on a EC2 instance!
